let ErrorMessage={
    INVALID_TOKEN:'Unauthorized user.',
    COUNTRY_EXIST:'Country name already exists.',
    INTERNAL_ERROR:'Internal Server Error.',
    INVALID_CREDENTIAL:'Invalid credentials.',
    SOMETHING_WRONG:'Something went wrong.',
    ALREADY_EXIST:'Already exists.',
    NO_TOKEN:'Please provide token.',
    EMAIL_NOT_REGISTERED:'Entered email is not registered with the account.',
    NOT_REGISTERED: "Entered email/mobile number is not registered.",
    RESET_PASSWORD_EXPIRED:'Your session has expired.',
    WRONG_PASSWORD:'Please enter a valid password.',
    INVALID_MOBILE:'Entered mobile number is not valid.',
    EMAIL_EXIST:'Entered email already exists.',
    NOT_FOUND:'Requested data not found.',
    USER_NOT_FOUND:'This user does not exist.',
    UPDATE_NOT:"Unexpected error during update, please try again.",
    MOBILE_EXIST:'This mobile number already exists.',
    USERNAME_EXIST:'This user name already exists.',
    USER_ID:'A valid User Id is required.',
    BLOCKED_BY_ADMIN:'You are not authorized, please get in touch with Admin.',
    DELETED_BY_ADMIN:'Your account is deleted, please get in touch with Admin.',
    FIELD_REQUIRED:'Fields are required.',
    OLD_PASSWORD:'You have provided an incorrect old password.',
    INCORRECT_JWT:'Invalid JWT token.',
    FORBIDDEN:'There was an error in sending an email.',
    INVALID_OTP:'Entered OTP is Invalid.',
    OTP_EXPIRED: "Entered OTP has expired, please try to resend OTP.",
    PASSMATCH:"Password does not match.",
    EVENT_EXISTS: "Event already added.",
    NOT_MATCH:"Password does not match.",
    CODE_NOT_FOUND:"Please enter a valid code.",
    LIST_EMPTY:"Empty List.",
    SESSION_STARTED: "Session has been started you can not join now.",
    SESSION_CREATED: "Session has been already created with that generated code.",
    SONG_NOT_REMOVE: "You cannot remove this song.",
    WALLET_EXIST: "Wallet address already exists.",
    ALREADY_UPVOTE: "You have already voted.",
    ALREADY_DOWNVOTE: "You have already downvoted.",
    TOKEN_EXISTS:"This Token already exist.",
    ALREADY_CANCEL:" This order already cancel.",
    DATA_NOT_FOUND: "Requested data not found .",
}

let SuccessMessage={
    SIGNUP_SUCCESSFULLY: "Thanks, You have successfully signed up.",
    LOGIN_SUCCESS:'Login successful.',
    CUSTOMER_VERIFY:'Customer verified successfully',
    FORGET_SUCCESS:'A password link has been sent to your registered email address.',
    RESET_SUCCESS:'Your password changed successfully .',
    PRODUCT_LIST_FETCH:' Product list fetched successfully.',
    USER_LIST_FETCH:'Successfully brought user list.',
    AUTHORIZATION:'This User is Authorized.',
    ACCOUNT_CREATION:'Your account has been created successfully.',
    EMAIL_SEND:"Otp has been sent to your registered Email successfully.",
    OTP_SEND:'Otp has been sent to your registered mobile number.',
    VERIFY_OTP:'OTP verified successfully.',
    PIN_SET:"Your Pin has been sent successfully.",
    PASSWORD_UPDATE: "Your password has been updated successfully.",
    DATA_SAVED:"Data is saved successfully.",
    DETAIL_GET:"Details have been fetched successfully.",
    DATA_FOUND:"Requested data found.",
    PROFILE_DETAILS:"Your profile details have been updated successfully.",
    STATUS_UPDATED:"Your Status has been changed successfully.",
    UPDATE_SUCCESS:"Successfully updated.",
    BLOCK_SUCCESS:"Successfully blocked.",
    UNBLOCK_SUCCESS:"Successfully activated.",
    DELETE_SUCCESS:"Successfully deleted.",
    SMS_SEND:"The SMS has been sent to the buddies successfully.",
    DESTINATION_ADD: "Destination has been added successfully.",
    SUB_ADMIN_CREATED:"Sub-admin has been created successfully.",
    EDIT_SUCC:"Successfully edit.",
    SESSION_CREATED:"Session created successfully.",
    CODE_GENERATED:"Code generated successfully.",
    JOIN_SUCCESS:"Session joined successfully.",
    INVITATION_SUCCESS:"Invitation sent.",
    SESSION_DETAILS:"Session Join user list.",
    REMOVE_SUCCESS:"Remove Successfully.",
    SESSION_SONG_ADD:"Song added in session.",
    SESSION_SONG_REMOVE:"Song removed from session.",
    SONGS_LIST:"Songs list founds.",
    LIST_EMPTY:"Empty List. ",
    PLAYLIST_ADD:"Playlist has been added successfully.",
    SESSION_END:"Session ended without adding playlist.",
    SESSION_START:"Session started successfully.",
    LIMIT_EXCEED:"Limit exceeded.",
    TRANSACTION_SUCCESS:"Transaction has been done successfully.",
    UP_VOTE:"Upvote has been done successfully.",
    DOWN_VOTE: "Downvote has been done successfully.",
    WISHED_DATA: "Added To Watchlist.",
    UNWISHED_DATA: "Removed From Watchlist.",
    APPROVED: "Data has been approved successfully.",
    REJECTED:"Data has been rejected successfully.",
    FEATURED:"Data has been featured successfully.",
    UNFEATURED:"Data has been unfeatured successfully.",
    ENABLE_SUCCESS:"Data has been enabled successfully.",
    DISABLE_SUCCESS:"Data has been disabled successfully.",
    ORDER_PLACED:"Order has been placed successfully.",
    ORDER_CANCEL:"Order Canceled Successfully.",
    UPDATE_SUCCESS:"Order Update Successfully.",
    BID_PLACED: "Bid has been placed successfully .",
    REPORTED:"Report on order has been done successfully .",
    BID_CANCELLED: "Bid canceled successfully.",
    SUCCESS_FETCH:"File uploaded Successfully.",

}
module.exports= {
    ErrorMessage,SuccessMessage
};

